BASE_URL = "https://qa-scooter.praktikum-services.ru/"
CREATE_COURIER_ENDPOINT = "api/v1/courier"
DELETE_COURIER_ENDPOINT = "api/v1/courier/"
COURIER_LOGIN_ENDPOINT = "api/v1/courier/login"
CREATE_ORDER_ENDPOINT = "api/v1/orders"
RECEIVING_ORDERS_LIST_ENDPOINT = "api/v1/orders"
